import { chromium } from 'playwright-core';
import http from 'http'; import fs from 'fs'; import path from 'path';
const DIST=path.resolve('dist');
const MIME={'.html':'text/html','.js':'application/javascript','.css':'text/css','.webp':'image/webp','.json':'application/json','.woff2':'font/woff2','.png':'image/png'};
const srv=await new Promise(r=>{const s=http.createServer((q,res)=>{let u=decodeURIComponent(q.url.split('?')[0]);if(u==='/')u='/index.html';const f=path.join(DIST,u);if(fs.existsSync(f)&&fs.statSync(f).isFile()){res.setHeader('Content-Type',MIME[path.extname(f)]||'application/octet-stream');fs.createReadStream(f).pipe(res);}else{res.statusCode=404;res.end();}});s.listen(4420,()=>r(s));});
const b=await chromium.launch({executablePath:'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe',headless:true});
const p=await b.newPage({viewport:{width:1440,height:900}});
const e=[]; p.on('pageerror',x=>e.push(x.message));
p.on('console',m=>{if(m.type()==='error')e.push('console: '+m.text());});
await p.goto('http://localhost:4420/',{waitUntil:'networkidle'});
await p.waitForTimeout(2500);
await p.evaluate(()=>window.scrollTo(0, 24000));
await p.waitForTimeout(2500);
console.log('errori:', e.length);
[...new Set(e)].slice(0,4).forEach(x=>console.log('  '+x.slice(0,180)));
await b.close(); srv.close();
