/**
 * shader.js — OGL fragment shader: due texture, quattro transizioni, carrello (pan).
 *
 * Due texture (t1, t2) passate allo shader:
 *   - Stato stabile: t1 = video/immagine attuale
 *   - Transizione:   t1 = ultimo fotogramma uscente, t2 = primo fotogramma entrante
 *
 * Quattro stili di transizione:
 *   mode 0: spazzata da sinistra — fronte rettilineo
 *   mode 1: spazzata da destra
 *   mode 2: spazzata dal centro verso i bordi
 *   mode 4: iride · 5: veneziana · 6: strisce · 7: pixel · 8: sfalsata
 *   mode 9: cerchio dall'angolo · 10: porte al centro
 *   mode 11: wipe inclinato · 12: iride espandi-contrai · 13: tenda opaca
 *   mode 3: dissolvenza colore — dissolve attraverso un colore pieno (ponte 2→3)
 *
 * Funzioni di servizio:
 *  - cover(uv, res, img)          : object-fit: cover DENTRO lo shader
 *  - sample(uv, zoom, pan)        : cover + zoom + pan
 *  - lift(c, grade)               : satura preservando luminanza Rec.709
 *  - hash(p)                      : value noise 2D senza texture
 */

var VERT = [
  'attribute vec2 position;',
  'varying vec2 vUv;',
  'void main() {',
  '  vUv = position * 0.5 + 0.5;',
  '  gl_Position = vec4(position, 0.0, 1.0);',
  '}',
].join('\n');

var FRAG = [
  'precision highp float;',
  'varying vec2 vUv;',
  '',
  'uniform sampler2D t1;',
  'uniform sampler2D t2;',
  'uniform float progress;',
  'uniform int mode;',
  'uniform float vel;',
  'uniform vec2 res;',
  'uniform vec2 img;',
  '',
  'uniform float zoomA;',
  'uniform float zoomB;',
  'uniform vec2 panA;',
  'uniform vec2 panB;',
  '',
  'uniform vec3 bridgeColor;',
  '',
  '/* ── cover(): object-fit: cover nello spazio UV ── */',
  'vec2 cover(vec2 uv, vec2 resolution, vec2 imageSize) {',
  '  float ca = resolution.x / resolution.y;',
  '  float ia = imageSize.x / imageSize.y;',
  '  if (ca > ia) {',
  '    uv.y = (uv.y - 0.5) * (ia / ca) + 0.5;',
  '  } else {',
  '    uv.x = (uv.x - 0.5) * (ca / ia) + 0.5;',
  '  }',
  '  return uv;',
  '}',
  '',
  '/* ── sample(): cover + zoom + pan per una texture ── */',
  'vec2 sample(vec2 uv, float zoom, vec2 pan) {',
  '  uv = cover(uv, res, img);',
  '  uv = (uv - 0.5) / zoom + 0.5;',
  '  uv += pan;',
  '  return uv;',
  '}',
  '',
  '/* ── lift(): satura preservando luminanza Rec.709 ── */',
  'vec3 lift(vec3 c, float g) {',
  '  float l = dot(c, vec3(0.2126, 0.7152, 0.0722));',
  '  return clamp(vec3(l) + (c - vec3(l)) * g, 0.0, 1.0);',
  '}',
  '',
  '/* ── tenda(): la banda non scambia A con B: passa per il COLORE.',
  '   Prima meta della corsa si riempie di bridgeColor, seconda meta lo',
  '   scopre su B. E cio che rende la tendina monocolore. */',
  'vec3 tenda(vec3 a, vec3 b, float p) {',
  '  if (p < 0.5) return mix(a, bridgeColor, p * 2.0);',
  '  return mix(bridgeColor, b, (p - 0.5) * 2.0);',
  '}',
  '',
  '/* ── tex4(): lettura morbida — quattro prelievi a croce, ampiezza',
  '   proporzionale all ingrandimento. Tiene la pittura pittorica quando',
  '   la camera scende sul dettaglio, invece di mostrare i pixel. ── */',
  'vec3 tex4(sampler2D t, vec2 uv, float zoom) {',
  '  float k = clamp((zoom - 1.25) * 0.55, 0.0, 1.35);',
  '  if (k <= 0.001) return texture2D(t, uv).rgb;',
  '  vec2 o = k / res;',
  '  vec3 c = texture2D(t, uv).rgb * 0.36;',
  '  c += texture2D(t, uv + vec2( o.x, 0.0)).rgb * 0.16;',
  '  c += texture2D(t, uv + vec2(-o.x, 0.0)).rgb * 0.16;',
  '  c += texture2D(t, uv + vec2(0.0,  o.y)).rgb * 0.16;',
  '  c += texture2D(t, uv + vec2(0.0, -o.y)).rgb * 0.16;',
  '  return c;',
  '}',
  '',
  '/* ── hash(): value noise 2D ── */',
  'float hash(vec2 p) {',
  '  p = fract(p * vec2(443.897, 441.423));',
  '  p += dot(p, p.yx + 19.19);',
  '  return fract((p.x + p.y) * p.x);',
  '}',
  '',
  'void main() {',
  '  vec2 uv = vUv;',
  '  vec3 result;',
  '',
  '  if (mode == 0) {',
  '    /* Spazzata DA SINISTRA: fronte verticale rettilineo che attraversa.',
  '       Rumore tenue (0.02): non si legge come effetto, ma toglie al fronte',
  '       la rigidita di un rettangolo di plastica. Il fronte va da -0.05 a 1.05 per',
  '       entrare e uscire del tutto dallo schermo. */',
  '    vec2 uvA = sample(uv, zoomA, panA);',
  '    vec2 uvB = sample(uv, zoomB, panB);',
  '    vec3 fromColor = texture2D(t1, uvA).rgb;',
  '    vec3 toColor   = texture2D(t2, uvB).rgb;',
  '    float n = hash(uv * 12.0) * 0.02;',
  '    float front = progress * 1.1 - 0.05;',
  '    float edge = smoothstep(front - 0.05 + n, front + 0.05 + n, uv.x);',
  '    result = mix(toColor, fromColor, edge);',
  '',
  '  } else if (mode == 1) {',
  '    /* Spazzata DA DESTRA: stesso fronte, verso opposto */',
  '    vec2 uvA = sample(uv, zoomA, panA);',
  '    vec2 uvB = sample(uv, zoomB, panB);',
  '    vec3 fromColor = texture2D(t1, uvA).rgb;',
  '    vec3 toColor   = texture2D(t2, uvB).rgb;',
  '    float n = hash(uv * 12.0) * 0.02;',
  '    float front = progress * 1.1 - 0.05;',
  '    float edge = smoothstep(front - 0.05 + n, front + 0.05 + n, 1.0 - uv.x);',
  '    result = mix(toColor, fromColor, edge);',
  '',
  '  } else if (mode == 2) {',
  '    /* Spazzata DAL CENTRO: si apre verso i due bordi.',
  '       d vale 0 al centro e 1 ai bordi. */',
  '    float d = abs(uv.x - 0.5) * 2.0;',
  '    vec2 uvA = sample(uv, zoomA, panA);',
  '    vec2 uvB = sample(uv, zoomB, panB);',
  '    vec3 fromColor = texture2D(t1, uvA).rgb;',
  '    vec3 toColor   = texture2D(t2, uvB).rgb;',
  '    float n = hash(uv * 12.0) * 0.02;',
  '    float front = progress * 1.1 - 0.05;',
  '    float edge = smoothstep(front - 0.05 + n, front + 0.05 + n, d);',
  '    result = mix(toColor, fromColor, edge);',
  '',
  '  } else if (mode == 4) {',
  '    /* IRIDE: un cerchio si apre dal centro. Il bordo e rotto dal rumore,',
  '       altrimenti sembra una maschera di cartone. */',
  '    vec2 uvA = sample(uv, zoomA, panA);',
  '    vec2 uvB = sample(uv, zoomB, panB);',
  '    vec3 fromColor = texture2D(t1, uvA).rgb;',
  '    vec3 toColor   = texture2D(t2, uvB).rgb;',
  '    float ar = res.x / res.y;',
  '    vec2 c = vec2((uv.x - 0.5) * ar, uv.y - 0.5);',
  '    float dist = length(c) / (0.5 * sqrt(1.0 + ar * ar));',
  '    float n = hash(uv * 14.0) * 0.03;',
  '    float raggio = progress * 1.15 - 0.05;',
  '    float edge = smoothstep(raggio - 0.07 + n, raggio + 0.07 + n, dist);',
  '    result = mix(toColor, fromColor, edge);',
  '',
  '  } else if (mode == 5) {',
  '    /* VENEZIANA: bande orizzontali che si aprono insieme. */',
  '    vec2 uvA = sample(uv, zoomA, panA);',
  '    vec2 uvB = sample(uv, zoomB, panB);',
  '    vec3 fromColor = texture2D(t1, uvA).rgb;',
  '    vec3 toColor   = texture2D(t2, uvB).rgb;',
  '    float bande = 9.0;',
  '    float dentro = fract(uv.y * bande);',
  '    float locale = clamp((progress * 1.15 - dentro * 0.30) / 0.85, 0.0, 1.0);',
  '    result = tenda(fromColor, toColor, locale);',
  '',
  '  } else if (mode == 6) {',
  '    /* STRISCE LARGHE: cinque bande verticali che si aprono UNA DOPO',
  '       L ALTRA da sinistra a destra. Poche e larghe, non un pettine:',
  '       ogni banda ha il suo ritardo, cosi la rivelazione spazza. */',
  '    vec2 uvA = sample(uv, zoomA, panA);',
  '    vec2 uvB = sample(uv, zoomB, panB);',
  '    vec3 fromColor = texture2D(t1, uvA).rgb;',
  '    vec3 toColor   = texture2D(t2, uvB).rgb;',
  '    float bande = 5.0;',
  '    float indice = floor(uv.x * bande);',
  '    float dentro = fract(uv.x * bande);',
  '    /* il ritardo cresce con l indice: la banda 0 parte subito,',
  '       l ultima parte quando la corsa e gia a meta */',
  '    float ritardo = indice / bande * 0.55;',
  '    float locale = clamp((progress - ritardo) / (1.0 - 0.55), 0.0, 1.0);',
  '    result = tenda(fromColor, toColor, locale);',
  '    float bordo = smoothstep(0.0, 0.02, dentro) * smoothstep(1.0, 0.98, dentro);',
  '    result *= mix(0.90, 1.0, bordo);',
  '',
  '  } else if (mode == 7) {',
  '    /* PIXEL: la scena si sgretola a blocchi, ognuno con la sua soglia. */',
  '    vec2 uvA = sample(uv, zoomA, panA);',
  '    vec2 uvB = sample(uv, zoomB, panB);',
  '    vec3 fromColor = texture2D(t1, uvA).rgb;',
  '    vec3 toColor   = texture2D(t2, uvB).rgb;',
  '    float griglia = 44.0;',
  '    vec2 blocco = floor(uv * vec2(griglia * (res.x / res.y), griglia));',
  '    float soglia = hash(blocco);',
  '    float edge = step(soglia, progress * 1.05);',
  '    result = mix(fromColor, toColor, edge);',
  '',
  '  } else if (mode == 8) {',
  '    /* SPAZZATA SFALSATA: bande che partono a tempi diversi. */',
  '    vec2 uvA = sample(uv, zoomA, panA);',
  '    vec2 uvB = sample(uv, zoomB, panB);',
  '    vec3 fromColor = texture2D(t1, uvA).rgb;',
  '    vec3 toColor   = texture2D(t2, uvB).rgb;',
  '    float bande = 7.0;',
  '    float indice = floor(uv.y * bande);',
  '    float ritardo = fract(sin(indice * 12.9898) * 43758.5453) * 0.35;',
  '    float locale = clamp((progress - ritardo) / (1.0 - 0.35), 0.0, 1.0);',
  '    result = tenda(fromColor, toColor, locale);',
  '',
  '  } else if (mode == 9) {',
  '    /* CERCHIO DALL ANGOLO: nasce nell angolo in basso a sinistra e si',
  '       apre fino a coprire tutto lo schermo. Il raggio arriva alla',
  '       diagonale piena, altrimenti l angolo opposto non verrebbe mai',
  '       raggiunto. Bordo rotto da un filo di rumore. */',
  '    vec2 uvA = sample(uv, zoomA, panA);',
  '    vec2 uvB = sample(uv, zoomB, panB);',
  '    vec3 fromColor = texture2D(t1, uvA).rgb;',
  '    vec3 toColor   = texture2D(t2, uvB).rgb;',
  '    float ar9 = res.x / res.y;',
  '    vec2 d9 = vec2((uv.x - 0.0) * ar9, uv.y - 0.0);',
  '    float diag = sqrt(ar9 * ar9 + 1.0);',
  '    float dist9 = length(d9) / diag;',
  '    float n9 = hash(uv * 11.0) * 0.025;',
  '    float raggio9 = progress * 1.16 - 0.06;',
  '    float edge9 = smoothstep(raggio9 - 0.09 + n9, raggio9 + 0.09 + n9, dist9);',
  '    result = mix(toColor, fromColor, edge9);',
  '',
  '  } else if (mode == 10) {',
  '    /* PORTE: la scena uscente si spacca a meta e le due parti scorrono',
  '       via, una a sinistra e una a destra, scoprendo quella sotto.',
  '       Non e una spazzata: le meta si MUOVONO davvero, quindi A va',
  '       ricampionata spostata, altrimenti si vedrebbe solo un taglio. */',
  '    float apertura = clamp(progress * 1.08, 0.0, 1.0);',
  '    float meta = apertura * 0.5;',
  '    float dalCentro = uv.x - 0.5;',
  '    float lato = dalCentro < 0.0 ? -1.0 : 1.0;',
  '    /* la meta uscente si prende il pixel che aveva prima di scorrere */',
  '    vec2 uvSpost = uv;',
  '    uvSpost.x = uv.x + lato * meta;',
  '    vec2 uvA = sample(uvSpost, zoomA, panA);',
  '    vec2 uvB = sample(uv, zoomB, panB);',
  '    vec3 fromColor = texture2D(t1, uvA).rgb;',
  '    vec3 toColor   = texture2D(t2, uvB).rgb;',
  '    /* dentro il varco si vede B; il bordo e appena ammorbidito */',
  '    float n10 = hash(uv * 10.0) * 0.012;',
  '    float varco = smoothstep(meta - 0.012 + n10, meta + 0.012 + n10, abs(dalCentro));',
  '    result = mix(toColor, fromColor, varco);',
  '    /* ombra sul taglio: le due ante hanno spessore */',
  '    float ombra = smoothstep(meta + 0.075, meta, abs(dalCentro)) * varco;',
  '    result *= mix(1.0, 0.55, ombra * apertura);',
  '',
  '  } else if (mode == 11) {',
  '    /* WIPE: fronte inclinato che attraversa da sinistra a destra.',
  '       La pendenza (slant) inclina il taglio: 0 sarebbe verticale,',
  '       0.42 da la diagonale ripida del riferimento. */',
  '    vec2 uvA = sample(uv, zoomA, panA);',
  '    vec2 uvB = sample(uv, zoomB, panB);',
  '    vec3 fromColor = texture2D(t1, uvA).rgb;',
  '    vec3 toColor   = texture2D(t2, uvB).rgb;',
  '    float slant = 0.42;',
  '    float xs = uv.x + (uv.y - 0.5) * slant;',
  '    /* la corsa parte prima di 0 e finisce dopo 1 per entrare e uscire',
  '       completamente dallo schermo, inclinazione compresa */',
  '    float fronte11 = progress * (1.0 + slant + 0.10) - (slant * 0.5 + 0.05);',
  '    float n11 = hash(uv * 13.0) * 0.015;',
  '    float e11 = smoothstep(fronte11 - 0.035 + n11, fronte11 + 0.035 + n11, xs);',
  '    result = mix(toColor, fromColor, e11);',
  '',
  '  } else if (mode == 12) {',
  '    /* IRIDE: un cerchio si espande da un punto fino a coprire tutto,',
  '       poi si contrae scoprendo la scena nuova. Due fasi, non una:',
  '       nella prima il colore copre A, nella seconda si ritira su B. */',
  '    vec2 uvA = sample(uv, zoomA, panA);',
  '    vec2 uvB = sample(uv, zoomB, panB);',
  '    vec3 fromColor = texture2D(t1, uvA).rgb;',
  '    vec3 toColor   = texture2D(t2, uvB).rgb;',
  '    float ar12 = res.x / res.y;',
  '    vec2 c12 = vec2((uv.x - 0.5) * ar12, uv.y - 0.5);',
  '    float d12 = length(c12) / (0.5 * sqrt(1.0 + ar12 * ar12));',
  '    float n12 = hash(uv * 12.0) * 0.02;',
  '    float p12 = progress * 2.0;',
  '    if (progress < 0.5) {',
  '      float r = p12 * 1.06;',
  '      float e = smoothstep(r - 0.07 + n12, r + 0.07 + n12, d12);',
  '      result = mix(bridgeColor, fromColor, e);',
  '    } else {',
  '      float r = (2.0 - p12) * 1.06;',
  '      float e = smoothstep(r - 0.07 + n12, r + 0.07 + n12, d12);',
  '      result = mix(bridgeColor, toColor, e);',
  '    }',
  '',
  '  } else if (mode == 13) {',
  '    /* TENDA OPACA: il velo entra e copre tutto, la scena cambia',
  '       mentre e nascosta, poi il velo esce. Tre tempi netti: copri,',
  '       scambia, scopri. Nessun bordo, nessuna forma: solo il colore. */',
  '    vec2 uvA = sample(uv, zoomA, panA);',
  '    vec2 uvB = sample(uv, zoomB, panB);',
  '    vec3 fromColor = texture2D(t1, uvA).rgb;',
  '    vec3 toColor   = texture2D(t2, uvB).rgb;',
  '    if (progress < 0.42) {',
  '      result = mix(fromColor, bridgeColor, progress / 0.42);',
  '    } else if (progress < 0.58) {',
  '      result = bridgeColor;',
  '    } else {',
  '      result = mix(bridgeColor, toColor, (progress - 0.58) / 0.42);',
  '    }',
  '',
  '  } else if (mode == 14) {',
  '    /* WIPE CON ARCO: come il wipe inclinato ma il fronte e curvo.',
  '       Il pannello resta fermo: e il tracciato di ritaglio che scopre.',
  '       La curvatura lo distingue dal wipe rettilineo, cosi due',
  '       giunzioni vicine non sembrano lo stesso effetto. */',
  '    vec2 uvA = sample(uv, zoomA, panA);',
  '    vec2 uvB = sample(uv, zoomB, panB);',
  '    vec3 fromColor = texture2D(t1, uvA).rgb;',
  '    vec3 toColor   = texture2D(t2, uvB).rgb;',
  '    float slant14 = 0.22;',
  '    float arco = sin(uv.y * 3.14159) * 0.16;',
  '    float xs14 = uv.x + (uv.y - 0.5) * slant14 - arco;',
  '    float fronte14 = progress * (1.0 + slant14 + 0.34) - (slant14 * 0.5 + 0.17);',
  '    float n14 = hash(uv * 13.0) * 0.012;',
  '    float e14 = smoothstep(fronte14 - 0.03 + n14, fronte14 + 0.03 + n14, xs14);',
  '    result = mix(toColor, fromColor, e14);',
  '',
  '  } else if (mode == 15) {',
  '    /* GRANA: dissolvenza a colore con soglia sgranata. Come la tenda,',
  '       ma il colore entra ed esce grano per grano, con la trama',
  '       della calce: ogni granello scatta al suo momento. */',
  '    vec2 uvA = sample(uv, zoomA, panA);',
  '    vec2 uvB = sample(uv, zoomB, panB);',
  '    vec3 fromColor = texture2D(t1, uvA).rgb;',
  '    vec3 toColor   = texture2D(t2, uvB).rgb;',
  '    float ar15 = res.x / res.y;',
  '    float g15 = hash(floor(vec2(uv.x * ar15, uv.y) * 96.0));',
  '    float g15b = hash(floor(vec2(uv.x * ar15, uv.y) * 96.0) + 31.7);',
  '    if (progress < 0.5) {',
  '      float t = progress * 2.0;',
  '      float m = smoothstep(t * 1.12 - 0.06, t * 1.12, g15);',
  '      result = mix(bridgeColor, fromColor, m);',
  '    } else {',
  '      float t = (progress - 0.5) * 2.0;',
  '      float m = smoothstep(t * 1.12 - 0.06, t * 1.12, g15b);',
  '      result = mix(toColor, bridgeColor, m);',
  '    }',
  '',
  '  } else if (mode == 16) {',
  '    /* VELO DI GRANA CONICA: tenda materica. Il pannello che copre non',
  '       e un colore piatto ma un velo ad anelli angolari: grani d ambra',
  '       sul colore di ponte, pagliuzze di calce, pendenza di fondo. */',
  '    vec2 uvA = sample(uv, zoomA, panA);',
  '    vec2 uvB = sample(uv, zoomB, panB);',
  '    vec3 fromColor = texture2D(t1, uvA).rgb;',
  '    vec3 toColor   = texture2D(t2, uvB).rgb;',
  '    float ar16 = res.x / res.y;',
  '    vec2 c161 = vec2((uv.x - 0.32) * ar16, uv.y - 0.40);',
  '    vec2 c162 = vec2((uv.x - 0.70) * ar16, uv.y - 0.65);',
  '    float a161 = atan(c161.y, c161.x) / 6.2831853;',
  '    float a162 = atan(c162.y, c162.x) / 6.2831853 + 0.25;',
  '    float f161 = fract(a161 * 171.0);',
  '    float f162 = fract(a162 * 327.0);',
  '    vec3 ambra16 = vec3(0.910, 0.690, 0.416);',
  '    vec3 calce16 = vec3(0.910, 0.875, 0.812);',
  '    vec3 velo = bridgeColor;',
  '    velo = mix(ambra16 * 0.5 + bridgeColor * 0.5, velo, step(0.286, f161));',
  '    velo = mix(velo, bridgeColor * 0.62, step(0.667, f161));',
  '    velo = mix(velo, calce16, step(0.636, f162) * 0.10);',
  '    /* niente moire al centro dei coni: li il velo torna piatto */',
  '    velo = mix(bridgeColor, velo, smoothstep(0.03, 0.14, length(c161)));',
  '    velo = mix(bridgeColor * 0.85, velo, smoothstep(0.02, 0.10, length(c162)));',
  '    /* pendenza 140 gradi: piu chiaro verso l alto-sinistra */',
  '    velo *= 0.90 + 0.20 * (1.0 - (uv.x * 0.45 + uv.y * 0.55));',
  '    if (progress < 0.42) {',
  '      result = mix(fromColor, velo, smoothstep(0.0, 0.42, progress));',
  '    } else if (progress < 0.58) {',
  '      result = velo;',
  '    } else {',
  '      result = mix(velo, toColor, smoothstep(0.58, 1.0, progress));',
  '    }',
  '',
  '  } else if (mode == 17) {',
  '    /* DISSOLVENZA PURA: mix diretto fra due fotogrammi adiacenti.',
  '       Serve al sub-frame: lo scrub fonde N con N+1 sulla parte',
  '       frazionaria e il film scorre liquido invece che a scatti. */',
  '    vec2 uvA = sample(uv, zoomA, panA);',
  '    vec2 uvB = sample(uv, zoomB, panB);',
  '    result = mix(tex4(t1, uvA, zoomA), tex4(t2, uvB, zoomB), progress);',
  '',
  '  } else {',
  '    /* Dissolvenza colore: dissolve attraverso un colore pieno */',
  '    vec2 uvA = sample(uv, zoomA, panA);',
  '    vec2 uvB = sample(uv, zoomB, panB);',
  '    vec3 fromColor = texture2D(t1, uvA).rgb;',
  '    vec3 toColor   = texture2D(t2, uvB).rgb;',
  '    /* progress arriva dal JS gia\' in [0,1] (smoothstep di transProgress).',
  '       Entrata fino a 0.28, pianoro piatto fino a 0.72, uscita fino a 1. */',
  '    float a = smoothstep(0.0,  0.28, progress);',
  '    float b = smoothstep(0.72, 1.0,  progress);',
  '    result = mix(mix(fromColor, bridgeColor, a), toColor, b);',
  '  }',
  '',
  '  /* ── FINITURA DI PALCO: la tela sotto la pittura. ──',
  '     Tre gesti minimi legati a vel, la velocita di scrub smorzata:',
  '     una vignetta che si stringe appena quando il film corre, una',
  '     grana di tela FERMA (il supporto non scorre con la pittura),',
  '     e un soffio di esposizione nel movimento. Da fermo quasi nulla:',
  '     la finitura si sente solo quando il lettore muove il tempo. */',
  '  vec2 vq = uv - 0.5;',
  '  float vig = 1.0 - smoothstep(0.30, 0.95, length(vq) * (1.0 + 0.35 * vel));',
  '  result *= mix(0.94, 1.0, vig);',
  '  float gr = fract(sin(dot(floor(uv * res / 2.5), vec2(12.9898, 78.233))) * 43758.5453);',
  '  result = clamp(result + (gr - 0.5) * (0.012 + 0.03 * vel), 0.0, 1.0);',
  '  result *= 1.0 + 0.04 * vel;',
  '  gl_FragColor = vec4(result, 1.0);',
  '}',
].join('\n');

export { VERT, FRAG };
